// <auto-generated />
using System;
using crud_it15.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace crud_it15.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("crud_it15.Models.Employee", b =>
            {
                b.Property<int>("EmployeeId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");
                MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("EmployeeId"));
                b.Property<decimal>("DailyRate").HasColumnType("decimal(18,2)");
                b.Property<string>("Department").HasMaxLength(100).HasColumnType("varchar(100)");
                b.Property<string>("FirstName").IsRequired().HasMaxLength(50).HasColumnType("varchar(50)");
                b.Property<string>("LastName").IsRequired().HasMaxLength(50).HasColumnType("varchar(50)");
                b.Property<string>("Position").HasMaxLength(100).HasColumnType("varchar(100)");
                b.HasKey("EmployeeId");
                b.ToTable("Employees");
            });

            modelBuilder.Entity("crud_it15.Models.Payroll", b =>
            {
                b.Property<int>("PayrollId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");
                MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PayrollId"));
                b.Property<DateTime>("Date").HasColumnType("datetime(6)");
                b.Property<decimal>("DaysWorked").HasColumnType("decimal(18,2)");
                b.Property<decimal>("Deduction").HasColumnType("decimal(18,2)");
                b.Property<int>("EmployeeId").HasColumnType("int");
                b.Property<decimal>("GrossPay").HasColumnType("decimal(18,2)");
                b.Property<decimal>("NetPay").HasColumnType("decimal(18,2)");
                b.HasKey("PayrollId");
                b.HasIndex("EmployeeId");
                b.ToTable("Payrolls");
            });

            modelBuilder.Entity("crud_it15.Models.Payroll", b =>
            {
                b.HasOne("crud_it15.Models.Employee", "Employee")
                    .WithMany("Payrolls")
                    .HasForeignKey("EmployeeId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
                b.Navigation("Employee");
            });

            modelBuilder.Entity("crud_it15.Models.Employee", b =>
            {
                b.Navigation("Payrolls");
            });
#pragma warning restore 612, 618
        }
    }
}
